version: '3.8'

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.16.4
        container_name: elasticsearch
        restart: always
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.security.http.ssl.enabled=false
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - elastic
        ulimits: # Increase memory map limits (important for Elasticsearch)
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 2G # Adjust memory allocation

    kibana:
        image: docker.elastic.co/kibana/kibana:8.16.4
        container_name: kibana
        restart: always
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - elasticsearch # Ensure Elasticsearch starts before Kibana

networks:
    elastic:
        driver: bridge

volumes:
    elasticsearch-data:
        driver: local